export const USER_LOGIN = 'USER_LOGIN';

export const ACCESSTOKEN = 'ACCESSTOKEN';

export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';

export const FETCH_SIGN_UP_SUCCESS =  'FETCH_SIGN_UP_SUCCESS';

export const GET_MOVIE_BY_GROUP = 'GET_MOVIE_BY_GROUP';

export const CLOSE_MODAL_PLAY_VIDEO = 'CLOSE_MODAL_PLAY_VIDEO';

export const OPEN_MODAL_PLAY_VIDEO = 'OPEN_MODAL_PLAY_VIDEO';

export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';

export const RESET_ERROR = 'RESET_ERROR';

export const CLOSE_MODAL_ALERT = 'CLOSE_MODAL_ALERT';

export const OPEN_MODAL_ALERT = 'OPEN_MODAL_ALERT';

export const SHOW_LOADING = 'SHOW_LOADING';

export const HIDE_LOADING = 'HIDE_LOADING';

export const FETCH_CINEMA_SYSTEM = "FETCH_CINEMA_SYSTEM";

export const FETCH_CINEMA = "FETCH_CINEMA";

export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS';

export const FETCH_ROOM_TICKET_SUCCESS = 'FETCH_ROOM_TICKET_SUCCESS';

export const ADD_TICKET_BOOKING = 'ADD_TICKET_BOOKING';

export const DELETE_TICKET_BOOKING = 'DELETE_TICKET_BOOKING';

export const POST_TICKET_SUCCESS = 'POST_TICKET_SUCCESS';
