export const USER_LOGIN = 'USER_LOGIN';

export const ACCESSTOKEN = 'ACCESSTOKEN';

export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';

export const FETCH_SIGN_UP_SUCCESS = 'FETCH_LOGIN_SUCCESS';

export const GET_MOVIE_BY_GROUP = 'GET_MOVIE_BY_GROUP';

export const CLOSE_MODAL_PLAY_VIDEO = 'CLOSE_MODAL_PLAY_VIDEO';

export const OPEN_MODAL_PLAY_VIDEO = 'OPEN_MODAL_PLAY_VIDEO';

export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';

export const RESET_ERROR = 'RESET_ERROR';

export const CLOSE_MODAL_ALERT = 'CLOSE_MODAL_ALERT';

export const OPEN_MODAL_ALERT = 'OPEN_MODAL_ALERT';

export const SHOW_LOADING = 'SHOW_LOADING';

export const HIDE_LOADING = 'HIDE_LOADING';
