export const USER_LOGIN = 'USER_LOGIN';
export const ACCESSTOKEN = 'ACCESSTOKEN';
export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_SIGN_UP = 'FETCH_SIGN_UP';
export const GET_MOVIE_BY_GROUP = 'GET_MOVIE_BY_GROUP';
export const CLOSE_MODAL_PLAY_VIDEO = 'CLOSE_MODAL_PLAY_VIDEO';
export const OPEN_MODAL_PLAY_VIDEO = 'OPEN_MODAL_PLAY_VIDEO';